### ISSUE TITLE
Package for the Arch User Repository.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [Nyancoins/nyancoin-client#5]
Hello There.

I just stumbled across this repository and was wondering if you would be interested in releasing a package on the [Arch User Repository](https://aur.archlinux.org)?

I will be glad to help you, in making a package.

**Comment by SharkyRawr** [comment]
Sounds great, I'll look into it!

**Comment by Aniket-Pradhan** [comment]
Sorry for closing the issue first.

I was unable to build the client. Then, I realized I was missing some dependencies. Forgot to reopen it again. :P

Anyways, if you could add the dependencies to the readme, that would be really helpful. Not everyone looks the wiki.

**Comment by SharkyRawr** [comment]
Sounds like a plan. 👍 

I have a question about the PKGBUILD I want to write for nyancoin, do you figure the GUI and daemon can be combined in to one package (customizable?) or should I make two packages `nyancoin-daemon` & `nyancoin` (for the whole thing)?

**Comment by Aniket-Pradhan** [comment]
Sorry, I don't know much about daemons, so I cannot comment on it. However, you can shoot up your doubts on [bbs](https://bbs.archlinux.org/viewforum.php?id=38), and maybe someone would be able to answer this.

Although, my gut says that you would require a separate package for the daemon, and you can combine the two packages to form a group or add the daemon as a dependency of the GUI package.

**Comment by Aniket-Pradhan** [comment]
Hey!

I was trying to build the client on some other PCs, and it is throwing an error on them. The error is something like this:

```
In file included from main.h:9,
                 from checkpoints.cpp:11:
bignum.h: At global scope:
bignum.h:52:24: error: invalid use of incomplete type ‘BIGNUM’ {aka ‘struct bignum_st’}
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:19,
                 from bignum.h:11,
                 from main.h:9,
                 from checkpoints.cpp:11:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM’ {aka ‘struct bignum_st’}
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from main.h:9,
                 from checkpoints.cpp:11:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:57:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
bignum.h:57:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
bignum.h:62:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
```

The complete error message is [here](https://pastebin.com/gyNtVW6x).

After a bit of Googling, I found that it is because of using an unsupported openssl libbrary. Currently, the system which got the error is using `openssl v1.1.1a`.

So, my question is what openssl version is recommended for the client (the version you are using), and whether there would be some patch for this in the future?

**Comment by SharkyRawr** [comment]
Try installing `openssl-1.0` (Version =<1.0).

I started working on a PKGBUILD over on my Gitlab: https://gitlab.com/Nyancoin/aur/blob/master/daemon/PKGBUILD  
It did compile for me but linking was an issue since Boost is linked to OpenSSL >=1.1 - which I read requires us to make a custom boost build that's linked to SSL =<1.0 - gahh.

**Comment by SharkyRawr** [comment]
I made some changes to get the wallet compiled with OpenSSL 1.1.1.a and Boost 1.69.0, could you try pulling the `ssl1.1` branch, building and testing it? Relevant commits for your review: https://github.com/Nyancoins/nyancoin-client/commits/ssl1.1

The `key_tests` unit-tests are not working properly for me -- but every other test seems to run fine so I don't think I broke anything.

**Comment by Aniket-Pradhan** [comment]
Sorry for replying late. I was having poor network connections for the past few days. :(

> Try installing `openssl-1.0` (Version =<1.0).

I installed `OpenSSL-1.0-1`, but that didn't work for me. Same error. :( Are you also using `OpenSSL-1.0`?

> Boost is linked to OpenSSL >=1.1 - which I read requires us to make a custom boost build that's linked to SSL =<1.0

I think the main motive should be to upgrade the client so that it works on the latest of its dependencies (i.e. OpenSSL >= 1.1 and boost >= 1.69). That's because most people have their systems updated and they would not downgrade their packages.

The `ssl1.1` branch also fails, but with a different error.

```
/usr/bin/ld: cannot find -ldb_cxx
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lminiupnpc
```
This is also because of OpenSSL. I guess you forgot to patch these parts?

**Comment by SharkyRawr** [comment]
You're missing the C++ bindings for berkeley db, openssl library (libssl, libcrypto) and miniupnpc `community/miniupnpc`

I recommend building BDB yourself or I made a PKGBUILD for it here: https://gitlab.com/Sharky/libdb-4.8-aur
Note that you need to add the library and include search paths for their respective directories in `/opt/BerkeleyDB-4.8` to the makefile.unix or nyancoin-qt.pro files if you use my PKGBUILD.

> I think the main motive should be to upgrade the client so that it works on the latest of its dependencies (i.e. OpenSSL >= 1.1 and boost >= 1.69). That's because most people have their systems updated and they would not downgrade their packages.

That's exactly what I did in the `ssl1.1` branch. :)

I got it to compile fine on my Manjaro laptop.

**Comment by SharkyRawr** [comment]
Wait a sec, interestingly enough I get the same error when using `makepkg` - but not when compiliing it manually.

**Comment by SharkyRawr** [comment]
I literally just did `cd src/nyancoin-client/src; make -f makefile.unix` and it linked everything together fine and finished the build. I think there is some PKGBUILD sandboxing going on.

**Comment by SharkyRawr** [comment]
I figured it out, I'm used to try and statically link programs like this but Arch doesn't have static libs to link to - so it fails with "cannot find".
I updated the PKGBUILD repo and it should work now.

**Comment by Aniket-Pradhan** [comment]
I missed the previous comment and have been scratching my head looking for libdb4.8 package on the community repos and the AUR :P . 

All I found was `db4.8` (I thought it was the required package) which doesn't work for Nyan client. Why don't you post the libdb4.8 onto AUR as well?

Moreover, I am able to compile the daemon now, and the PKGBUILD works pretty well. :beer:

**Comment by Aniket-Pradhan** [comment]
A few points for the PKGBUILD, though.

1. You might want to remove those extra methods like `epoch`, `groups`, `backup`... if you are not using them.
2. There is no use for the `prepare()` block in this use-case.

And that's pretty much it. ;)

**Comment by SharkyRawr** [comment]
If everything is working for you and there are no more issues regarding this, I'll close this issue. Feel free to open a new issue if anything arises. :)
